### ISSUE TITLE
Ability to Track Mod Files

### ISSUE THREAD

**Issue by NightPotato** [NightPotato/MBModManager#12]
For operations like Uninstall and Disable Mod, we need to know the file associated with each mod which will be stored in ``ModInfo``. Using this method we can track, update, disable, and uninstall each mod from the Mod Management Section.

**Comment by Amenofisch** [comment]
This could be stored in a SQLite DB or something like that...

**Comment by NightPotato** [comment]
Currently I had it planned for ``ModInfo`` to contain this and when the mod is installed I set the it. Then save a list of the installed mods to a file near the executable. Like ``settings.json`` or a ``data.json`` file. If SQLite would be worth the implementation then we can do it that way.

**Comment by Amenofisch** [comment]
We could add a new variable to the `ModInfo` class, with like a `string[]` that contains the direct path's to the files. But yeah that works with JSON as well.
