### ISSUE TITLE
Are the Task.Delay's actually needed?

### ISSUE THREAD

**Issue by Amenofisch** [NightPotato/MBModManager#22]
https://github.com/NightPotato/MBModManager/blob/74bffb6e214e644745b635f27a19736cfd554aa2/Events/InstallEvents.cs#L40
https://github.com/NightPotato/MBModManager/blob/74bffb6e214e644745b635f27a19736cfd554aa2/Events/InstallEvents.cs#L51
https://github.com/NightPotato/MBModManager/blob/74bffb6e214e644745b635f27a19736cfd554aa2/Events/InstallEvents.cs#L63
https://github.com/NightPotato/MBModManager/blob/74bffb6e214e644745b635f27a19736cfd554aa2/Events/InstallEvents.cs#L70
https://github.com/NightPotato/MBModManager/blob/74bffb6e214e644745b635f27a19736cfd554aa2/Events/InstallEvents.cs#L75

Title says it all, isn't there a way to get rid of these?

**Comment by NightPotato** [comment]
Only a few are really needed like errors because else they disappear before you can read the message. I only used them because I was testing and needed it to sit at a stage for some time before proceeding. They can be removed in a clean up commit.
