### ISSUE TITLE
(Suggestion) Load the game's path from the registry

### ISSUE THREAD

**Issue by Amenofisch** [NightPotato/MBModManager#3]
Let me know if you need help with this.

It was already implemented in the old manager so I can easily send you the code for it.

**Basic concept:**

1. Check for registry entry for game's path
2. If found return it
3. If not found ask the user to give the game's path

**Comment by NightPotato** [comment]
I planned to do this but for my local testing install, I have to manually set the path as I keep two versions of the game installed at any given time. Will be implemented before v1.0.0 release is ready.
